# XGB with Solar Power Ramp Events

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

## Importing the dataset

In [2]:
os.getcwd()
os.chdir('../datasets')
# dataset = pd.read_csv('Social_Network_Ads.csv')
dataset = pd.read_csv('rampdata66.csv')
# X = dataset.iloc[:, [2, 3]].values
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 66].values
# X = dataset.iloc[:, :-1]
# y = dataset.iloc[:, 66]
dataset.head()

V1        V2        V3        V4        V5        V6        V7  \
0  0.001610  0.001852  0.445164  0.710982  0.482693  0.346400  0.786719   
1  0.127630  0.085961  0.548310  0.907729  0.999993  0.607910  0.184483   
2  0.034725  0.109288  0.510308  0.922363  0.999993  0.598586  0.159467   
3  0.033372  0.276992  0.473963  0.927030  0.999993  0.604930  0.140143   
4  0.171606  0.153857  0.456074  0.928770  0.999993  0.595534  0.121081   

         V8        V9       V10  ...    V58  V59  V60  V61  V62  V63  V64  \
0  0.296912  0.212884  0.414958  ...      4    2    2    2    2    2    1   
1  0.370349  0.051022  0.696017  ...      2    2    2    2    2    4    4   
2  0.365388  0.054600  0.720091  ...      2    2    2    2    2    2    2   
3  0.369037  0.092530  0.730662  ...      4    4    4    2    2    2    2   
4  0.371288  0.086637  0.736614  ...      2    4    4    2    2    2    2   

   V65  V66  Class  
0    2    2      4  
1    2    2      2  
2    2    2      2  
3    2    4      4  
4    4    4      4  

[5 rows x 67 columns]

### Choose Some Features from the Input Features

In [3]:
# a=[7,8,21,22,40,41,57,58]
# a=[7,8,9,21,22,23,40,41,42,57,58,59]
# a=[7,8,9,21,22,23,33,34,35,40,41,42,50,51,52,57,58,59]
# a=[6,7,8,9,20,21,22,23,32,33,34,35,39,40,41,42,49,50,51,52,56,57,58,59]
# a=[6,7,8,9,20,21,22,23,27,29,32,33,34,35,39,40,41,42,46,48,49,50,51,52,56,57,58,59,63,66]

a=[20,21,22,23,27,29,33,34,35,39,40,41,42,46,48,49,56,57,58,59,63,65,66]

# a=n=np.arange(50,66)
# a=n=np.arange(55,66)

# n=np.arange(0,66)
n=66
xn = set(range(n)) - set(a)
print('a=',a)
print('xn=',xn)

xf=np.delete(X,np.s_[a], axis=1)

xf.shape

a= [20, 21, 22, 23, 27, 29, 33, 34, 35, 39, 40, 41, 42, 46, 48, 49, 56, 57, 58, 59, 63, 65, 66]
xn= {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 24, 25, 26, 28, 30, 31, 32, 36, 37, 38, 43, 44, 45, 47, 50, 51, 52, 53, 54, 55, 60, 61, 62, 64}


C:\Users\Mhdella\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.


(3828, 44)

In [4]:
X=xf

## Encoding categorical data

In [5]:
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# labelencoder_X = LabelEncoder()
# X[ : , 1] = labelencoder_X.fit_transform(X[ : , 1])
# X

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [7]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

### Cross-validation for the model: 
Fitting 2 folds for each of 80 candidates, totalling 160 fits,  (it takes time about < 5mins)

https://scikit-learn.org/stable/modules/model_evaluation.html
{'learning_rate': 0.01, 'max_depth': 4, 'n_estimators': 500}

In [8]:
from sklearn import metrics   ##Additional scklearn functions
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV   #Perforing grid search

from xgboost.sklearn import XGBClassifier
model = XGBClassifier(criterion = 'entropy', random_state=0, class_weight='balanced')

test_params = {'n_estimators':[100, 200, 300, 400, 500], 'max_depth':[2,4,8,12], 'learning_rate': [0.01, 0.1, 0.5, 1]}

grid = GridSearchCV(estimator = model, param_grid = test_params, n_jobs=4, 
                    scoring='f1_weighted',cv=2, verbose=3)

grid.fit(X_train,y_train)
print(grid.best_params_)

Fitting 2 folds for each of 80 candidates, totalling 160 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:   33.0s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:  3.0min
[Parallel(n_jobs=4)]: Done 160 out of 160 | elapsed:  3.4min finished


{'learning_rate': 0.01, 'max_depth': 4, 'n_estimators': 500}


### Fitting the model
Evaluate metric(s) by cross-validation and also record fit/score times.

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html

https://scikit-learn.org/stable/modules/cross_validation.html

In [64]:
from sklearn import metrics   ##Additional scklearn functions
from sklearn.model_selection import cross_validate
from sklearn.metrics.scorer import make_scorer
from sklearn.metrics import confusion_matrix
from xgboost.sklearn import XGBClassifier

# params={'learning_rate': 0.01, 'max_depth': 4, 'n_estimators': 500}

params={'max_depth': 12,'min_samples_split': 100, 'n_estimators': 300, 'learning_rate': 0.1}
# classifier = XGBClassifier(**params, criterion = 'entropy', random_state=0, class_weight='balanced')
classifier = XGBClassifier(**params, criterion = 'entropy', random_state=0, scale_pos_weight=[7.30534351,  0.74186047, 30.87096774,  0.40277778])

cv_results = cross_validate(classifier, X, y, cv=2)

## Random Search for Feature Selection

In [65]:
# from sklearn.model_selection import cross_val_score

# result = []# Number of iterations
# # N_search = 300# Random seed initialization
# N_search = 10# Random seed initialization

# np.random.seed(1)
# for i in range(N_search):
#     # Generate a random number of features
#     N_columns =  list(np.random.choice(range(X.shape[1]),1)+1)
# #     N_columns =  list(np.random.choice(range(5),1)+1)

    
#     # Given the number of features, generate features without replacement
#     columns = list(np.random.choice(range(X.shape[1]), N_columns, replace=False))
# #     columns = list(np.random.choice(range(5), N_columns, replace=False))

    
#     # Perform k-fold cross validation
# #     scores = cross_val_score(classifier,X[:,columns], y, cv=2, scoring="accuracy")
# #     scores = cross_val_score(classifier,X[:,columns], y, cv=2, scoring="f1_micro")
#     scores = cross_val_score(classifier,X[:,columns], y, cv=2, scoring="f1_weighted")


#     # Store the result
#     result.append({'columns':columns,'performance':np.mean(scores)})
#     # Sort the result array in descending order for performance measure
# result.sort(key=lambda x : -x['performance'])

inputs=X[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 24, 25, 26, 28, 30, 31, 32, 36, 37, 38, 43, 44, 45, 47, 50, 51, 52, 53, 54, 55, 60, 61, 62, 64]

By using class_weight='balanced', with search  N_search=1000 and just use the best selected features that gives True Hi_Ramps= 82
slsected features=[35, 38, 1, 19, 9, 14, 39, 37, 24, 7, 6, 5, 22, 18, 32, 10, 4, 15, 13]  19

gives True_Hi_Ramps=83 and False_Hi_Ramps=57.


In [66]:
# # result[0]
# # X[:,result[0]['columns']]
# print(result[0]['columns'])
# print(len(result[0]['columns']))
# # print(result[N_search-1]['columns'])
# # print(pd.Series(range(1,5))) 

In [67]:
cv_results

C:\Users\Mhdella\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)


{'fit_time': array([5.3753376 , 5.68182206]),
 'score_time': array([0.10675693, 0.09373879]),
 'test_score': array([0.84751958, 0.86356508]),
 'train_score': array([1., 1.])}

In [68]:
sum(y_train.shape+y_test.shape)

3828

## Single metric evaluation using cross_validate

In [69]:
sorted(cv_results.keys())                         
['fit_time', 'score_time', 'test_score']
cv_results['test_score']    

array([0.84751958, 0.86356508])

## Making the Confusion Matrix
#### We can use this value to calculate the new performance measure with this subset of the features.

In [70]:
from sklearn.model_selection import cross_val_predict
# y_pred = cross_val_predict(classifier, X, y, cv=2)
# y_pred = cross_val_predict(classifier, X[:,result[0]['columns']], y, cv=2)

y_pred = cross_val_predict(classifier, X, y, cv=2)

# y_pred = cross_val_predict(classifier, X[:,result[N_search-1]['columns']], y, cv=2)
# y_pred = cross_val_predict(classifier, X[:,result[N_search-(N_search-1)]['columns']], y, cv=2)


from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred, y)
cm

array([[  56,   40,    0,    1],
       [  74, 1032,    2,  195],
       [   0,    1,   10,    3],
       [   1,  217,   19, 2177]], dtype=int64)

In [71]:
print('True Hi_Ramps=',cm[0,0]+cm[2,2])
print('False Hi_Ramps=',cm[1,0]+cm[2,0]+cm[3,0]+cm[0,2]+cm[1,2]+cm[3,2])

True Hi_Ramps= 66
False Hi_Ramps= 96


In [63]:
from sklearn.metrics import f1_score
f1_score(y, y_pred, average=None)

array([0.49122807, 0.7959892 , 0.44444444, 0.90897704])

####  Multiple metric evaluation using cross_validate 

In [50]:
# # scores = cross_validate(classifier, X, y, cv=2, scoring=('f1_weighted'), return_train_score=True)
# scores = cross_validate(classifier, X[:,result[0]['columns']], y, cv=2, scoring=('f1_weighted'), 
#                            return_train_score=True)

In [51]:
# # print(scores['train_f1_weighted'])   
# # print(scores['f1_weighted'])   
# scores
# # train_f1_weighted

## Analysis on the outcomes y, (classes of solar ramp events)

In [52]:
y.shape
len(y)
print('C1=', len(y[y==1]),'C2=', len(y[y==2]),
      'C3=', len(y[y==3]),'C4=', len(y[y==4]))

C1= 131 C2= 1290 C3= 31 C4= 2376


In [53]:
X.shape

(3828, 44)

In [54]:
classifier

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, criterion='entropy', gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=12, min_child_weight=1,
       min_samples_split=100, missing=None, n_estimators=300, n_jobs=1,
       nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1,
       scale_pos_weight=[7.30534351, 0.74186047, 30.87096774, 0.40277778],
       seed=None, silent=True, subsample=1)

In [40]:
###n_samples / (n_classes * np.bincount(y))
3828 / (4 * np.bincount(y))

C:\Users\Mhdella\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([        inf,  7.30534351,  0.74186047, 30.87096774,  0.40277778])

In [31]:
np.bincount(y)

array([   0,  131, 1290,   31, 2376], dtype=int64)

In [38]:
np.bincount(y==0)

array([3828], dtype=int64)